### ISSUE TITLE
Links don't open in default browser

### ISSUE THREAD

**Issue by colinodell** [adambirds/recipe-office365-owa#7]
**OS:** Ubuntu Linux 16.04.3 LTS

**Franz:** 5.0.0-beta.12-304

**Expected Behavior:** Clicking on a link in an email opens that link in my default browser (Chrome) just like other recipes do.

**Actual Behavior:** Link is opened in (what appears to be) a new Electron window as part of Franz.  This window has no URL bar.

![peek 2017-11-06 07-18](https://user-images.githubusercontent.com/202034/32440786-b97be03a-c2c2-11e7-96e5-e2ae840882ed.gif)

**Comment by alecive** [comment]
Same behavior. Ubuntu linux 14.04.3 LTS, Franz 5.0.0-beta.12-304. May be connected to https://github.com/meetfranz/franz/issues/135 https://github.com/meetfranz/franz/issues/185 and others.

**Comment by adambirds** [comment]
Same problem that is mentioned in meetfranz/franz#185, issue is with the app itself rather than the recipe.

**Comment by colinodell** [comment]
According to the preferred solution for https://github.com/meetfranz/franz/issues/185:

> **add a check in the Github recipe** to open links that are leaving github.com in a browser window

> that should apply to the GitHub recipe AND **everything else that may have the same issue**.

Based on my understanding, that type of check still needs to be implemented here.  Is that the same interpretation you have @adambirds?

**Comment by adambirds** [comment]
I guess so, but no further info was given in meetfranz/franz#185 about how that check would work, also makes it difficult with a site as complex as a Microsoft site, (we all know how bad they are) as the site isn't always the same domain name.

I certainly haven't got any ides on how this could be implemented. I'd say probably one to point towards the guys over at Franz who may be able to provide the info on what needs doing.
